import Head from 'next/head'
// import Image from 'next/image'
import Navbar from '../components/Navbar'
import { useState } from 'react'
import Tasks from '../components/Tasks'
import Footer from '../components/Footer'
import { useTask } from '../hooks/useTask'
// import Axios from 'axios'

export default function Home({ data }) {
  const [title, setTitle] = useState('')
  const [error, setError] = useState(null)
  const [emptyFields, setEmptyFields] = useState([])
  const {tasks, dispatch} = useTask()

  const addTask = async (e) => {
    e.preventDefault()

    const task = {title}

    const res = await fetch(`${process.env.NEXT_PUBLIC_URL}/api/todo`, {
      method: 'POST',
      body:JSON.stringify(task),
      headers: {
        'Content-Type': 'application/json'
      }
    })

    const data = await res.json()

    if(!res.ok) {
      setError(data.error)
      setEmptyFields(data.emptyFields)
    }

    if(res.ok){
      setError(null)
      console.log('new task added', data)
      setTitle('')
      setEmptyFields([])

      dispatch({
        type: 'CREATE_TASK',
        payload: data
    })
    }
  }

  return (
    <div>
      <Head>
        <title>To Do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar />
        <section className='h-[50vh] bg-[#6C00FF]'>
          <div className='container mx-auto flex flex-col h-full justify-center'>
            <h1 className='text-white font-bold text-6xl'>
              Manage your daily tasks <span className='text-[#F2DEBA]'>Here !</span>
            </h1>
            <div className='mt-10 bg-white w-[50%] p-8 rounded-xl shadow-xl'>
              <form className='flex flex-col items-start gap-5'>
                <label htmlFor='title' className='text-md font-semibold'>
                  Task Title
                </label>
                <input
                  id='title'
                  type="text"
                  placeholder='Prepare my Resume'
                  className={emptyFields.includes('title') ? "outline-none border-b-2 border-red-500 py-4 text-lg w-full" : "outline-none border-b-2 py-4 text-lg w-full"}
                  onChange={(e) => setTitle(e.target.value)}
                  value={title}
                />
                <button
                  className='bg-[#6C00FF] rounded-lg text-white px-8 py-3 self-end font-bold'
                  onClick={addTask}
                >
                  <span className='text-[#F2DEBA]'>+</span>{" "}Add
                </button>
                {error && 
                  <div className='text-red-500'>
                      {error}
                  </div>
                }
              </form>
            </div>
          </div>
        </section>

        <section className='bg-[#3C4048]'>
          <div className='container mx-auto py-12 '>
            <Tasks />
          </div>
        </section>
        
        <Footer />
      </>
    </div>
  )
}
